import "./style.css";
import { SCREENS, type Screen } from "../../../core/src/ui.js";

const labels: Record<Screen, string> = {
  splash: "Splash & initialization", "first-run": "First-run setup", home: "Home", browse: "Browse all games", categories: "Categories", search: "Search", "search-results": "Search results", "game-details": "Game details", screenshots: "Screenshots", "download-queue": "Download queue", "download-details": "Active download", installed: "Installed games", updates: "Available updates", storage: "Storage overview", settings: "Settings", "network-diagnostics": "Network diagnostics", "repository-status": "Repository status", about: "About & licenses", "error-details": "Error details", offline: "Offline catalog"
};
const icons: Partial<Record<Screen, string>> = { home: "⌂", browse: "▦", search: "⌕", "download-queue": "↓", installed: "✓", updates: "↻", settings: "⚙", about: "i" };
const primary: Screen[] = ["home", "browse", "search", "download-queue", "installed", "updates", "settings", "about"];
let current: Screen = "home"; let navIndex = 0; let offline = false;

const app = document.querySelector<HTMLDivElement>("#app")!;
app.innerHTML = `<div class="shell"><header><img src="/logo.svg" alt="Playstore HB"><div class="connection"><span class="pulse"></span><span id="connection">Repository ready · empty catalog</span><time>${new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time></div></header><div class="body"><nav aria-label="Primary"></nav><main id="main" tabindex="-1"></main></div><footer><span><kbd>Arrows</kbd> Navigate</span><span><kbd>Enter</kbd> Select</span><span><kbd>Esc</kbd> Back</span><span><kbd>F</kbd> Search</span><span><kbd>M</kbd> Menu</span><span class="sim">DESKTOP SIMULATOR · NO PS4 INSTALLS</span></footer></div>`;
const nav = document.querySelector("nav")!; const main = document.querySelector<HTMLElement>("#main")!;

function renderNavigation(): void {
  nav.innerHTML = primary.map((screen, index) => `<button class="nav-item ${screen === current ? "active" : ""}" data-screen="${screen}" data-index="${index}" aria-current="${screen === current ? "page" : "false"}"><span class="nav-icon">${icons[screen] ?? "•"}</span><span>${labels[screen]}</span></button>`).join("") + `<div class="nav-meta"><strong>Catalog</strong><span>Sequence 0</span><span>No approved games</span><span class="safe">✓ Signed-cache policy active</span></div>`;
  nav.querySelectorAll<HTMLButtonElement>("button").forEach((button) => button.addEventListener("click", () => openScreen(button.dataset.screen as Screen)));
}

function emptyCatalog(): string { return `<section class="hero"><div><span class="eyebrow">CURATED HOMEBREW · CATALOG SEQUENCE 0</span><h1>Real games only.<br><em>Review comes first.</em></h1><p>The production catalog is intentionally empty. Releases appear here only after licensing, redistribution, package, and real-hardware review.</p><div class="actions"><button class="primary" data-open="repository-status">View repository status</button><button data-open="browse">Browse catalog</button></div></div><div class="container-mark"><span>↓</span><b>HB</b></div></section><section class="status-grid"><article><span class="metric">0</span><h2>Approved releases</h2><p>No fictional or unreviewed catalog entries are displayed.</p></article><article><span class="metric cyan">OFF</span><h2>Telemetry</h2><p>Diagnostics stay on this device unless you export them.</p></article><article><span class="metric purple">LKG</span><h2>Offline safety</h2><p>Last-known-good catalogs are retained atomically.</p></article></section>`; }

function settings(): string { return `<div class="page-head"><span class="eyebrow">ACCESSIBILITY & BEHAVIOR</span><h1>Settings</h1><p>Desktop settings simulate the same controller-first model used by the console client.</p></div><div class="settings">${[["Confirm button","Cross","Respect system mapping where available"],["Concurrent downloads","1","Conservative default; maximum 3"],["Keep downloaded PKGs","Off","Remove after successful installation"],["Automatic update checks","On","Signed catalogs only"],["Media cache limit","512 MiB","Bounded least-recently-used cache"],["Background artwork","On","Can be disabled"],["Animation level","Full","Reduced motion overrides this"],["Text size","Normal","Large and extra-large available"],["High contrast","Off","Adds non-color focus cues"],["Reduced motion","Off","Disables nonessential transitions"],["Repository channel","Stable","No arbitrary production URL"],["Diagnostics logging","Off","Redacted local logs only"]].map((row) => `<button class="setting"><span><strong>${row[0]}</strong><small>${row[2]}</small></span><b>${row[1]}</b></button>`).join("")}</div>`; }
function generic(title: string): string { return `<div class="page-head"><span class="eyebrow">PLAYSTORE HOMEBREW</span><h1>${title}</h1><p>This screen is wired into the shared navigation model. The empty production state is intentional and no invented content is substituted.</p></div><div class="empty"><div class="empty-icon">${icons[current] ?? "◇"}</div><h2>Nothing to show yet</h2><p>${offline ? "Offline mode is active. Installed titles and saved download state remain available." : "No approved catalog records exist. Retry, inspect repository status, or return home."}</p><button class="primary" data-open="home">Return home</button></div>`; }
function about(): string { return `<div class="page-head"><span class="eyebrow">VERSION 0.1.0 · DESKTOP TESTED</span><h1>About Playstore HB</h1><p>Real homebrew games. Direct to your PS4.</p></div><section class="about"><h2>Independent homebrew</h2><p>Playstore HB is an independent homebrew project. It is not affiliated with or endorsed by Sony Interactive Entertainment, Google, or any commercial game publisher.</p><h2>Content and integrity</h2><p>A matching hash proves file identity—not safety. Each release also requires legal review and actual PS4 launch verification before publication.</p><h2>Licenses</h2><p>First-party code is MIT licensed. Third-party notices are generated from pinned dependencies. No proprietary SDK component or production signing key is included.</p><button data-open="repository-status">Repository status</button></section>`; }
function repository(): string { return `<div class="page-head"><span class="eyebrow">TRUST STATUS</span><h1>Repository status</h1></div><div class="checks"><article><b>✓</b><span><strong>Production catalog is empty</strong><small>Zero games; no development fixtures can be published.</small></span></article><article><b>✓</b><span><strong>Signature required</strong><small>New manifests are rejected before parsing unless Ed25519 verification succeeds.</small></span></article><article><b>✓</b><span><strong>Downgrade protection</strong><small>Highest accepted sequence is persisted.</small></span></article><article class="warn"><b>!</b><span><strong>Production key not provisioned</strong><small>The checked-in empty manifest is not a published release.</small></span></article><button id="offline-toggle">${offline ? "Return online" : "Simulate offline mode"}</button></div>`; }

function render(): void {
  renderNavigation();
  main.dataset.screen = current;
  if (current === "home") main.innerHTML = emptyCatalog(); else if (current === "settings") main.innerHTML = settings(); else if (current === "about") main.innerHTML = about(); else if (current === "repository-status") main.innerHTML = repository(); else main.innerHTML = generic(labels[current]);
  main.querySelectorAll<HTMLElement>("[data-open]").forEach((button) => button.addEventListener("click", () => openScreen(button.dataset.open as Screen)));
  document.querySelector("#offline-toggle")?.addEventListener("click", () => { offline = !offline; document.querySelector("#connection")!.textContent = offline ? "Offline · last-known-good catalog" : "Repository ready · empty catalog"; render(); });
}
function openScreen(screen: Screen): void { current = screen; const index = primary.indexOf(screen); if (index >= 0) navIndex = index; render(); main.focus(); }
function move(delta: number): void { navIndex = Math.max(0, Math.min(primary.length - 1, navIndex + delta)); openScreen(primary[navIndex]!); }
window.addEventListener("keydown", (event) => { if (event.key === "ArrowDown") move(1); else if (event.key === "ArrowUp") move(-1); else if (event.key === "Escape") openScreen("home"); else if (event.key.toLowerCase() === "f") openScreen("search"); else if (event.key.toLowerCase() === "m") openScreen("settings"); });
let gamepadDebounce = 0;
function pollGamepad(): void { const pad = navigator.getGamepads?.()[0]; if (pad && performance.now() - gamepadDebounce > 180) { if (pad.buttons[12]?.pressed) { move(-1); gamepadDebounce = performance.now(); } else if (pad.buttons[13]?.pressed) { move(1); gamepadDebounce = performance.now(); } else if (pad.buttons[1]?.pressed) { openScreen("home"); gamepadDebounce = performance.now(); } } requestAnimationFrame(pollGamepad); }
render(); requestAnimationFrame(pollGamepad);
void SCREENS;
