import { randomUUID, scryptSync, timingSafeEqual } from "node:crypto";
import Fastify, { type FastifyInstance, type FastifyRequest } from "fastify";
import { z } from "zod";
import { validateCatalog, signCatalog, verifySignedCatalog, type TrustedKey } from "../../../core/src/index.js";
import type { CatalogGame, CatalogManifest } from "../../../core/src/types.js";
import type { AuditEvent, Principal, Repository, Role, Submission } from "./model.js";
import { MemoryRepository } from "./repository.js";

declare module "fastify" { interface FastifyRequest { principal?: Principal } }
const roleRank: Record<Role, number> = { submitter: 1, reviewer: 2, publisher: 3, administrator: 4 };
const createSchema = z.object({ name: z.string().min(1).max(120), developer: z.string().min(1).max(120), publisher:z.string().max(120).optional(),contact: z.string().min(3).max(320), sourceUrl: z.url().startsWith("https://"), homepage: z.url().startsWith("https://"), version: z.string().regex(/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/),releaseDate:z.string().optional(),summary:z.string().max(240).optional(), description: z.string().min(1).max(12000), codeLicense: z.string().min(1), dataLicense: z.string().min(1), evidence: z.string().min(1),titleId: z.string().regex(/^[A-Z]{4}\d{5}$/), contentId: z.string().regex(/^[A-Z]{2}\d{4}-[A-Z]{4}\d{5}_00-[A-Z0-9]{16}$/), categories: z.string().min(1),controls:z.string().max(4000).optional(),players:z.string().max(20).optional(),attribution:z.string().max(4000).optional(),changelog:z.string().max(8000).optional(),testedFirmware:z.string().max(120).optional(),testedModel:z.enum(["fat","slim","pro"]).optional(),knownIssues:z.string().max(4000).optional(),packageUpload:z.string().max(128).optional(),coverArtwork:z.string().max(128).optional(),backgroundArtwork:z.string().max(128).optional(),screenshots:z.string().max(1000).optional(), originalFiles: z.union([z.literal("on"), z.boolean()]).optional(), localMultiplayer: z.union([z.literal("on"), z.boolean()]).optional(), onlineMultiplayer: z.union([z.literal("on"), z.boolean()]).optional() }).strict();
const reviewChecks = z.object({ realAndFunctional: z.literal(true), launchesOnPs4: z.literal(true), matchesProject: z.literal(true), redistributionDocumented: z.literal(true), licenseTextsPresent: z.literal(true), screenshotsAuthentic: z.literal(true), noImproperCommercialData: z.literal(true), compatibilityTruthful: z.literal(true), reviewedHashMatches: z.literal(true), notes: z.string().max(4000).default("") }).strict();

export interface ApiOptions { repository?: Repository; tokens?: Record<string, Principal>; signingPrivateKeyPem?: string; trustedKeys?: TrustedKey[]; logger?: boolean; allowedOrigins?: string[] }
export async function createApi(options: ApiOptions = {}): Promise<FastifyInstance> {
  const repository = options.repository ?? new MemoryRepository();
  const tokens = options.tokens ?? { "development-admin-token": { subject: "local-admin", role: "administrator" } };
  const allowedOrigins=options.allowedOrigins??["http://127.0.0.1:5174","http://localhost:5174"];
  const app = Fastify({ logger: options.logger ?? false, bodyLimit: 25 * 1024 * 1024, requestIdHeader: "x-request-id", genReqId: () => randomUUID(), trustProxy: false });
  const rate = new Map<string,{window:number;count:number}>();
  app.addHook("onRequest", async (request, reply) => { const origin=request.headers.origin;if(origin&&allowedOrigins.includes(origin))reply.header("access-control-allow-origin",origin).header("vary","origin").header("access-control-allow-headers","authorization,content-type,idempotency-key,x-request-id").header("access-control-allow-methods","GET,POST,PUT,OPTIONS");if(request.method==="OPTIONS")return reply.code(204).send();const key=request.ip; const now=Date.now(); const item=rate.get(key); if(!item||now-item.window>60_000)rate.set(key,{window:now,count:1});else if(++item.count>120)return reply.code(429).send(problem(request,"RATE_LIMITED","Too many requests.")); reply.header("x-request-id",request.id).header("x-content-type-options","nosniff").header("referrer-policy","no-referrer").header("content-security-policy","default-src 'none'"); });
  app.addHook("preHandler", async (request) => { const header=request.headers.authorization; if(header?.startsWith("Bearer ")) { const principal=tokens[header.slice(7)]; if(principal) request.principal=principal; } });
  app.setErrorHandler((error, request, reply) => { const message=error instanceof Error?error.message:"Unknown request error";const code=message==="NOT_FOUND"?404:400; return reply.code(code).send(problem(request,code===404?"NOT_FOUND":"INVALID_REQUEST",code===404?"The requested record does not exist.":message)); });
  app.get("/health", async () => ({ status:"ok",service:"playstorehb-catalog-api",version:"0.1.0" }));
  app.get("/v1/catalog", async (_request,reply) => reply.header("cache-control","public, max-age=60").send((await repository.getPublishedCatalog()).manifest));
  app.get("/v1/catalog/signature", async () => { const c=await repository.getPublishedCatalog(); return { key_id:c.manifest.key_id,signature:c.signature }; });
  app.get("/v1/games", async () => (await repository.getPublishedCatalog()).manifest.games);
  app.get<{Params:{id:string}}>("/v1/games/:id", async (request,reply) => { const game=(await repository.getPublishedCatalog()).manifest.games.find((g)=>g.id===request.params.id); return game??reply.code(404).send(problem(request,"NOT_FOUND","Game not found.")); });
  app.get("/v1/categories", async () => { const games=(await repository.getPublishedCatalog()).manifest.games; return [...new Set(games.flatMap((game)=>game.categories))].sort().map((id)=>({id,count:games.filter((g)=>g.categories.includes(id)).length})); });
  app.get("/v1/client/releases/latest", async () => ({ version:"0.1.0", status:"desktop-tested", ps4HardwareTested:false, url:null }));
  app.post("/v1/admin/games", {preHandler:authorize("submitter")}, async (request,reply) => { const data=createSchema.parse(request.body);const existing=await repository.listSubmissions();if(existing.some((s)=>s.data.titleId===data.titleId||s.data.contentId===data.contentId))throw new Error("DUPLICATE_IDENTIFIER"); const now=new Date().toISOString(); const submission:Submission={id:randomUUID(),status:"draft",submitter:request.principal!.subject,createdAt:now,updatedAt:now,data,automatedChecks:automatedChecks(data)}; const created=await repository.createSubmission(submission,idempotency(request)); await audit(repository,request,"submission.create",created.id,{}); return reply.code(201).send(created); });
  app.put<{Params:{id:string}}>("/v1/admin/games/:id",{preHandler:authorize("submitter")},async(request)=>{const raw=request.body as Record<string,unknown>;const wrapped=raw&&typeof raw==="object"&&("game" in raw||"submission" in raw);const data=wrapped&&raw.submission?createSchema.parse(raw.submission):wrapped?undefined:createSchema.parse(raw);const game=wrapped&&raw.game?validateGameRecord(raw.game):undefined;const existing=await repository.listSubmissions();if(data&&existing.some((s)=>s.id!==request.params.id&&(s.data.titleId===data.titleId||s.data.contentId===data.contentId)))throw new Error("DUPLICATE_IDENTIFIER"); const value=await repository.updateSubmission(request.params.id,(s)=>{ if(s.submitter!==request.principal!.subject&&request.principal!.role!=="administrator")throw new Error("FORBIDDEN"); if(s.status!=="draft")throw new Error("IMMUTABLE_SUBMISSION");const nextData=data??s.data;return{...s,data:nextData,...(game?{game}:{}),automatedChecks:automatedChecks(nextData as z.infer<typeof createSchema>),updatedAt:new Date().toISOString()};});await audit(repository,request,"submission.update",value.id,{gameMetadataAttached:Boolean(game)});return value; });
  app.post<{Params:{id:string}}>("/v1/admin/games/:id/packages",{preHandler:authorize("submitter")},async(request)=>{ const body=z.object({filename:z.string().regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,126}\.pkg$/),sizeBytes:z.number().int().positive().max(100*1024**3),sha256:z.string().regex(/^[a-f0-9]{64}$/),mime:z.literal("application/octet-stream"),storageKey:z.string().regex(/^quarantine\/[A-Za-z0-9/_-]+\.pkg$/)}).parse(request.body); const result=await repository.updateSubmission(request.params.id,(s)=>({...s,data:{...s.data,package:body},updatedAt:new Date().toISOString()}));await audit(repository,request,"package.attach",result.id,{filename:body.filename,sizeBytes:body.sizeBytes});return result;});
  app.post<{Params:{id:string}}>("/v1/admin/games/:id/media",{preHandler:authorize("submitter")},async(request)=>{const body=z.object({kind:z.enum(["cover","background","icon","screenshot"]),mime:z.enum(["image/png","image/jpeg","image/webp"]),width:z.number().int().min(64).max(7680),height:z.number().int().min(64).max(4320),sha256:z.string().regex(/^[a-f0-9]{64}$/),storageKey:z.string().regex(/^quarantine\/[A-Za-z0-9/_-]+\.(png|jpe?g|webp)$/)}).parse(request.body);await audit(repository,request,"media.attach",request.params.id,{kind:body.kind,width:body.width,height:body.height});return{accepted:true,automatedValidation:"passed",legalApproval:false};});
  app.post<{Params:{id:string}}>("/v1/admin/games/:id/submit-review",{preHandler:authorize("submitter")},async(request)=>{const result=await repository.updateSubmission(request.params.id,(s)=>{if(s.submitter!==request.principal!.subject&&request.principal!.role!=="administrator")throw new Error("FORBIDDEN");if(!s.game)throw new Error("MISSING_COMPLETE_GAME_METADATA");if(s.automatedChecks.some((c)=>!c.passed))throw new Error("AUTOMATED_CHECKS_FAILED");return{...s,status:"submitted",updatedAt:new Date().toISOString()};});await audit(repository,request,"submission.submit-review",result.id,{});return result;});
  app.post<{Params:{id:string}}>("/v1/admin/games/:id/approve",{preHandler:authorize("reviewer")},async(request)=>{const checks=reviewChecks.parse(request.body);const {notes,...booleanChecks}=checks;const result=await repository.updateSubmission(request.params.id,(s)=>{if(s.status!=="submitted")throw new Error("INVALID_STATE");if(s.submitter===request.principal!.subject)throw new Error("INDEPENDENT_REVIEW_REQUIRED");const at=new Date().toISOString();return{...s,status:"approved",review:{reviewer:request.principal!.subject,reviewedAt:at,checks:booleanChecks,notes},approval:{reviewer:request.principal!.subject,approvedAt:at},updatedAt:at};});await audit(repository,request,"submission.approve",result.id,{});return result;});
  app.post("/v1/admin/catalog/publish",{preHandler:authorize("publisher")},async(request)=>{const body=z.object({manifest:z.unknown(),signature:z.string().optional()}).parse(request.body);const manifest=validateCatalog(body.manifest,{production:true});const submissions=await repository.listSubmissions();for(const game of manifest.games){const approved=submissions.find((s)=>s.status==="approved"&&s.game?.id===game.id&&s.game.package.sha256===game.package.sha256);if(!approved)throw new Error(`MISSING_MATCHING_APPROVAL:${game.id}`);}let signature=body.signature;if(signature){const current=await repository.getPublishedCatalog();verifySignedCatalog(manifest,signature,options.trustedKeys??[],{highestSequence:current.manifest.catalog_sequence,clientVersion:"0.1.0",production:true});}else{if(!options.signingPrivateKeyPem)throw new Error("EXTERNAL_SIGNATURE_REQUIRED");signature=signCatalog(manifest,options.signingPrivateKeyPem);}const published=await repository.publish({manifest,signature},request.principal!.subject,request.id,idempotency(request));return published;});
  app.get("/v1/admin/audit-log",{preHandler:authorize("reviewer")},async()=>repository.listAudit());
  return app;
}

function authorize(minimum:Role){return async(request:FastifyRequest,reply:import("fastify").FastifyReply)=>{if(!request.principal)return reply.code(401).send(problem(request,"UNAUTHENTICATED","A bearer token is required."));if(roleRank[request.principal.role]<roleRank[minimum])return reply.code(403).send(problem(request,"FORBIDDEN","This role cannot perform that action."));};}
function problem(request:FastifyRequest,code:string,message:string){return{error:{code,message,requestId:request.id}};}
function idempotency(request:FastifyRequest):string|undefined{const value=request.headers["idempotency-key"];return typeof value==="string"?value:undefined;}
function automatedChecks(data:z.infer<typeof createSchema>){const development=JSON.stringify(data).toUpperCase().includes("DEVELOPMENT TEST DATA");return[{code:"IDENTIFIERS",passed:true,message:"Identifiers match format; database duplicate check is required before approval."},{code:"LICENSE_FIELDS",passed:Boolean(data.codeLicense&&data.dataLicense&&data.evidence),message:"License fields are present; automated validation is not legal approval."},{code:"DEVELOPMENT_MARKER_DETECTION",passed:true,message:development?"DEVELOPMENT TEST DATA marker detected; production publication will refuse this record.":"No development marker detected."}];}
function validateGameRecord(value:unknown):CatalogGame{const now=new Date();const manifest:CatalogManifest={schema_version:1,catalog_version:`${now.toISOString().slice(0,10).replaceAll("-",".")}.9999`,catalog_sequence:9999,generated_at:now.toISOString(),expires_at:new Date(now.getTime()+86400_000).toISOString(),minimum_client_version:"0.1.0",key_id:"submission-validation",channel:"development",games:[value as CatalogGame]};return validateCatalog(manifest).games[0]!;}
async function audit(repository:Repository,request:FastifyRequest,action:string,resource:string,details:Record<string,unknown>){const event:AuditEvent={id:randomUUID(),at:new Date().toISOString(),actor:request.principal?.subject??"anonymous",action,resource,requestId:request.id,details};await repository.recordAudit(event);}
export function hashPassword(password:string,salt=Buffer.from(randomUUID())):{salt:string;hash:string}{const hash=scryptSync(password,salt,64);return{salt:salt.toString("base64"),hash:hash.toString("base64")};}
export function verifyPassword(password:string,saltBase64:string,hashBase64:string):boolean{const actual=scryptSync(password,Buffer.from(saltBase64,"base64"),64);const expected=Buffer.from(hashBase64,"base64");return actual.length===expected.length&&timingSafeEqual(actual,expected);}
