import { generateKeyPairSync } from "node:crypto";
import { afterEach, describe, expect, it } from "vitest";
import type { FastifyInstance } from "fastify";
import { createApi } from "../../apps/catalog-api/src/app.js";
import { MemoryRepository } from "../../apps/catalog-api/src/repository.js";
import { developmentGame } from "../fixtures/catalog.js";
import { signCatalog } from "../../core/src/signedCatalog.js";

const tokens={submit:{subject:"alice",role:"submitter" as const},review:{subject:"bob",role:"reviewer" as const},publisher:{subject:"pat",role:"publisher" as const},admin:{subject:"root",role:"administrator" as const}};
const body={name:"DEVELOPMENT TEST DATA",developer:"Test suite",contact:"test@example.invalid",sourceUrl:"https://source.test.invalid/project",homepage:"https://home.test.invalid",version:"1.0.0",description:"Test-only submission object.",codeLicense:"MIT",dataLicense:"CC0-1.0",evidence:"TEST-ONLY",titleId:"PSTB10001",contentId:"IV0000-PSTB10001_00-DEVELOPMENTFIX01",categories:"arcade"};
let app:FastifyInstance|undefined;afterEach(async()=>{await app?.close();app=undefined;});
describe("catalog API",()=>{
  it("serves public health and empty catalog",async()=>{app=await createApi({tokens});expect((await app.inject({method:"GET",url:"/health"})).statusCode).toBe(200);const catalog=await app.inject({method:"GET",url:"/v1/catalog"});expect(catalog.json().games).toEqual([]);});
  it("requires authentication for submission",async()=>{app=await createApi({tokens});expect((await app.inject({method:"POST",url:"/v1/admin/games",payload:body})).statusCode).toBe(401);});
  it("enforces independent approval and records audit",async()=>{const repository=new MemoryRepository();app=await createApi({tokens,repository});const create=await app.inject({method:"POST",url:"/v1/admin/games",headers:{authorization:"Bearer submit","idempotency-key":"once"},payload:body});expect(create.statusCode).toBe(201);const id=create.json().id as string;expect((await app.inject({method:"PUT",url:`/v1/admin/games/${id}`,headers:{authorization:"Bearer submit"},payload:{submission:body,game:developmentGame()}})).statusCode).toBe(200);expect((await app.inject({method:"POST",url:`/v1/admin/games/${id}/submit-review`,headers:{authorization:"Bearer submit"}})).statusCode).toBe(200);const checks={realAndFunctional:true,launchesOnPs4:true,matchesProject:true,redistributionDocumented:true,licenseTextsPresent:true,screenshotsAuthentic:true,noImproperCommercialData:true,compatibilityTruthful:true,reviewedHashMatches:true,notes:"Test workflow only"};expect((await app.inject({method:"POST",url:`/v1/admin/games/${id}/approve`,headers:{authorization:"Bearer submit"},payload:checks})).statusCode).toBe(403);expect((await app.inject({method:"POST",url:`/v1/admin/games/${id}/approve`,headers:{authorization:"Bearer review"},payload:checks})).statusCode).toBe(200);const audit=await app.inject({method:"GET",url:"/v1/admin/audit-log",headers:{authorization:"Bearer review"}});expect(audit.json().map((e:{action:string})=>e.action)).toContain("submission.approve");});
  it("enforces upload filename and MIME validation",async()=>{app=await createApi({tokens});const create=await app.inject({method:"POST",url:"/v1/admin/games",headers:{authorization:"Bearer submit"},payload:body});const id=create.json().id;const result=await app.inject({method:"POST",url:`/v1/admin/games/${id}/packages`,headers:{authorization:"Bearer submit"},payload:{filename:"../evil.pkg",sizeBytes:10,sha256:"0".repeat(64),mime:"text/plain",storageKey:"outside"}});expect(result.statusCode).toBe(400);});
  it("rejects duplicate title and content identifiers",async()=>{app=await createApi({tokens});expect((await app.inject({method:"POST",url:"/v1/admin/games",headers:{authorization:"Bearer submit"},payload:body})).statusCode).toBe(201);expect((await app.inject({method:"POST",url:"/v1/admin/games",headers:{authorization:"Bearer submit"},payload:body})).statusCode).toBe(400);});
  it("supports explicit development admin CORS without credentials cookies",async()=>{app=await createApi({tokens});const response=await app.inject({method:"OPTIONS",url:"/v1/admin/games",headers:{origin:"http://127.0.0.1:5174"}});expect(response.statusCode).toBe(204);expect(response.headers["access-control-allow-origin"]).toBe("http://127.0.0.1:5174");});
  it("verifies an external signature before an atomic empty-catalog publication",async()=>{const repository=new MemoryRepository();const pair=generateKeyPairSync("ed25519");const privatePem=pair.privateKey.export({type:"pkcs8",format:"pem"}).toString();const publicPem=pair.publicKey.export({type:"spki",format:"pem"}).toString();const now=new Date();const manifest={schema_version:1 as const,catalog_version:`${now.toISOString().slice(0,10).replaceAll("-",".")}.2`,catalog_sequence:1,generated_at:now.toISOString(),expires_at:new Date(now.getTime()+86400_000).toISOString(),minimum_client_version:"0.1.0",key_id:"test-production-key",channel:"stable" as const,games:[]};app=await createApi({tokens,repository,trustedKeys:[{id:manifest.key_id,publicKeyPem:publicPem}]});const response=await app.inject({method:"POST",url:"/v1/admin/catalog/publish",headers:{authorization:"Bearer publisher","idempotency-key":"publish-once"},payload:{manifest,signature:signCatalog(manifest,privatePem)}});expect(response.statusCode).toBe(200);expect((await repository.getPublishedCatalog()).manifest.catalog_sequence).toBe(1);expect((await repository.listAudit()).map((event)=>event.action)).toContain("catalog.publish");});
});
